[Appearance]
color_scheme_path=@CONFIG@/qt6ct/colors/default.conf
style=kvantum
icon_theme=Papirus-Dark
standard_dialogs=default
custom_palette=true

[Fonts]
fixed="JetBrainsMono Nerd Font,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Inter,11,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
